spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testDB;DB_CLOSE_DELAY=-1;MODE=MYSQL
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    defer-datasource-initialization: true

  sql:
    init:
      data-locations: classpath:sql/data.sql
      mode: always
      encoding: UTF-8

logging:
  level:
    root: info
    com.musinsa.category: debug
    org.hibernate.SQL: debug
